### ISSUE TITLE
Allow otther mobs from mods such as Wild Mobs, Exotic Birds, Animals+, or Zoocraft Discoveries to spawn in Middle-earth.

### ISSUE THREAD

**Issue by MagmaSlime123** [AutumnalModding/LilyflowerTweaks#2]
Title.

https://www.curseforge.com/minecraft/mc-mods/the-animals-plus
https://www.curseforge.com/minecraft/mc-mods/exotic-birds
https://www.curseforge.com/minecraft/mc-mods/wild-mobs-mod
https://www.curseforge.com/minecraft/mc-mods/zoocraft-discoveries

Some mobs from certain mods are duplicates or wouldn't fit the theme of Middle-earth (Exotic Birds' Phoenix). These wouldn't spawn.
LOTR does have Birds, but they don't really do much. If Exotic Birds is loaded for example, LOTR's birds wouldn't spawn, and Exotic Birds' birds would be their replacement.

**Comment by DoubleHypercube** [comment]
Retagging as 'not planned'.
