### ISSUE TITLE
Gandalf Remains Unkillable

### ISSUE THREAD

**Issue by ThuOfNumenor** [AutumnalModding/LilyflowerTweaks#5]
Modifying the enableGreyWandererDeath property in the combat config file does not seem to have effect, in version 1.2.0 with LOTRMod v36.15, and all other features remaining as defaulted.  I have tried with fire, explosions, melee damage, and fall damage.  As far as I can tell, there is no logged information I can share, but please let me know if there is any information missing or would like provided.

**Comment by DoubleHypercube** [comment]
You're right - it doesn't seem to work, I'll look into it.
(Sorry for the late reply!)

**Comment by DoubleHypercube** [comment]
Fixed in 82dd734.
(However - the config variable DID change, to `enableGWDeath`.)

**Comment by DoubleHypercube** [comment]
@ThuOfNumenor So it turns out this never actually got fixed - oops!
I was using the _deobf_ name instead of the SRG one. Commit d052156fa3cbef4f19e39fdaa78be3db8262931b actually, really, properly fixes this now with a coremod.
