### ISSUE TITLE
Modded Combat System Additions not Recognized

### ISSUE THREAD

**Issue by ThuOfNumenor** [AutumnalModding/LilyflowerTweaks#6]
Modifications to the additionalCombatItems property in the combat config for equipment of mods initialized after lotweakr are not recognized, in version 2.0 with LOTRMod v36.15, with all other config options unmodified.  This was tested using items from Atum 2 v0.6.77 (successfully), Minecraft (successfully), Smithing In the "90'S" v1.1.0 (ineffectually), and Netherlicious v3.2.8 (ineffectually), albeit not in a clean instance.  Reinstating the "ZZZ_" prefix fixes this issue.

**Comment by DoubleHypercube** [comment]
Fixed (hopefully) - now registered in postinit instead of preinit.
